-- Database: Amazon
-- username: test
-- password: test


CREATE TABLE BOOK(
LINK_OF_THE_IMAGE VARCHAR(512) DEFAULT NULL, 
RANKING VARCHAR(64) DEFAULT NULL, 
TITLE VARCHAR(256) DEFAULT NULL,
AUTHOR VARCHAR(128) DEFAULT NULL,
PRICE VARCHAR(64) DEFAULT NULL,
TIMESTAMP TIME DEFAULT NULL
);
